const categories = [
    {name: 'General Knowledge', code: 9},
    {name: 'Books', code: 10},
    {name: 'Films', code: 11},
    {name: 'Music', code: 12},
    {name: 'Musicals and Theaters', code: 13},
    {name: 'Television', code: 14},
    {name: 'Video Games', code: 15},
    {name: 'Board Games', code: 16},
    {name: 'Science and Nature', code: 17},
    {name: 'Computers', code: 18},
    {name: 'Mathematics', code: 19},
    {name: 'Mythology', code: 20},
    {name: 'Sports', code: 21},
    {name: 'Geography', code: 22},
    {name: 'History', code: 23},
    {name: 'Politics', code: 24},
    {name: 'Art', code: 25},
    {name: 'Celebrities', code: 26},
    {name: 'Animals', code: 27},
    {name: 'Vehicles', code: 28},
    {name: 'Comics', code: 29},
    {name: 'Gadgets', code: 30},
    {name: 'Anime and Manga', code: 31},
    {name: 'Cartoon and Animations', code: 32}
];
export default categories;
